# Setup
title:        ChenJava
tagline:      A responsive theme for your project on GitHub Pages
url:          "http://chen-node.com/ChenJava"
baseurl:      "/ChenJava"
paginate:     1

# About/contact
author:
  name:       Chen Xie
  url:        http://github.com/neilChenXie

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
